services:
  hmpps-prisoner-finance-advances-api:
    image: ghcr.io/ministryofjustice/hmpps-prisoner-finance-advances-api:latest
    networks:
      - hmpps
    container_name: hmpps-prisoner-finance-advances-api
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/8080"]
    environment:
      - SERVER_PORT=8080
      - HMPPS_AUTH_URL=http://hmpps-auth:8080/auth
      - SPRING_PROFILES_ACTIVE=dev

  hmpps-prisoner-finance-advances-db:
    container_name: hmpps-prisoner-finance-advances-db
    image: postgres:16.15
    restart: always
    networks:
      - hmpps
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=advances
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5

  hmpps-auth:
    image: ghcr.io/ministryofjustice/hmpps-auth:latest
    networks:
      - hmpps
    container_name: hmpps-auth
    ports:
      - "8090:8080"
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/8080"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev
      - APPLICATION_AUTHENTICATION_UI_ALLOWLIST=0.0.0.0/0

networks:
  hmpps:
