hmpps-auth:
  url: "http://localhost:8090/auth"

general-ledger-api:
  url: http://localhost:8084
  client:
    id: hmpps-prisoner-finance-general-ledger-api
    secret: clientsecret

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true


spring:
  application:
    name: hmpps-prisoner-finance-advances-api

  datasource:
    url: 'jdbc:postgresql://${DB_SERVER:localhost:5437}/${DB_NAME:advances}?sslmode=prefer'
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
